version: "3.5"

services:
  postgres:
    image: postgres:16
    hostname: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
